<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
    <RootNamespace>SmartRoutine.Tests</RootNamespace>
    <AssemblyName>SmartRoutine.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CustomWFUI">
      <HintPath>..\lib\CustomWFUI\CustomWFUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\lib\GitHubSelfUpdater\*.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartRoutine\SmartRoutine.csproj" />
  </ItemGroup>

</Project>
